### PR TITLE
Improvements to the page changing div. Fixes issue #4. 

### PR DESCRIPTION
**Pull request by nicyuvi**
### What?
Made improvements to the UI for the page div and also added some active state functionality. 
### Why?
Fixes issue #4. 
### How?
- Used React Bootstrap Pagination Component
- Used Material UI Hooks API to apply custom styles
- Applied a brute force solution to apply active states to the current page
### Anything Else?
The active states functionality is brute force and could use some refactoring if possible. Please let me know if there is anything else I can improve on. Thanks!

### CODE REVIEW

**Review by version0chiro — APPROVED** [review]
Great work!

**Review by version0chiro — COMMENTED** [review]
These changes look really good, it would also be great if you can add the functionality of changing page with just clicking on the page number too! Other than that its really nice.

@nicyuvi

**Comment by nicyuvi** [comment]
Thank you! And I can work on that if I have some time! @version0chiro

**Comment by version0chiro** [comment]
Yea sure take your time.

**Pull request merged**
