### PR TITLE
README file updated

### PR DESCRIPTION
**Pull request by nishant219**
README file updated...
* Image attached
* Info about Hacktoberfest attached

### CODE REVIEW

**Review by version0chiro — APPROVED** [review]
LGTM, Thanks for this update

**Comment by version0chiro** [comment]
Why have you added hacktoberfest in the readme?

**Comment by nishant219** [comment]
> Why have you added hacktoberfest in the readme?

The issue raised on June 1, => Make a better readme #32
and this issue was labeled as hacktoberfest so that's why I added it in the readme file.
That's my 2nd PR, so I have little prior experience so Your feedback will be fruitful sir.

**Comment by alok722** [comment]
@version0chiro why did you merged this PR, this PR is totally irrelevant.

**Comment by version0chiro** [comment]
I have reverted back don't worry @alok722, It happened by mistake

**Pull request merged**
